version: "3.8"
services:
  server:
    build:
      context: ../..
      dockerfile: cloud/aws/Dockerfile.aggregator
    container_name: local_aefl_server
  client1:
    build:
      context: ../..
      dockerfile: cloud/aws/Dockerfile.client
    container_name: local_aefl_client1
  client2:
    build:
      context: ../..
      dockerfile: cloud/aws/Dockerfile.client
    container_name: local_aefl_client2
  client3:
    build:
      context: ../..
      dockerfile: cloud/aws/Dockerfile.client
    container_name: local_aefl_client3
  client4:
    build:
      context: ../..
      dockerfile: cloud/aws/Dockerfile.client
    container_name: local_aefl_client4
  client5:
    build:
      context: ../..
      dockerfile: cloud/aws/Dockerfile.client
    container_name: local_aefl_client5
